events {
    worker_connections 1024;
}

http {
    upstream express {
        server express:3000;
    }

    server {
        server_tokens off;

        server_name aboba.com.ru www.aboba.com.ru;
        listen 80;

        server_name localhost;


        location / {
            return 301 https://$host$request_uri;
        }
    }


    server {
        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/aboba.com.ru/fullchain.pem; # managed b>
        ssl_certificate_key /etc/letsencrypt/live/aboba.com.ru/privkey.pem; # managed>
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        location / {
            proxy_pass https://express;
        }
    }

    server {
        if ($host = aboba.com.ru) {
            return 301 https://$host$request_uri;
        } # managed by Certbot


        listen 80 default_server;
        listen [::]:80 default_server;
        server_name aboba.com.ru;
        return 404; # managed by Certbot
    }

}
