events {
    worker_connections 1024;
}

http {

    upstream express {
        server express:3000;
    }


    server {
        server_tokens off;


        listen 80;

        server_name localhost;


        location / {
            proxy_pass http://express;
        }
    }
}
